on:
  workflow_dispatch:

jobs:
  import-policy-flaws:
    runs-on: ubuntu-latest
    steps:

      - name: import flaws as issues
        uses: julz0815/ado-workitems-action@main
        with:
          ado-token: ${{ secrets.ADO_PAT }}
          ado-org: jtotzek
          ado-project: MeijerTest
          work-item-type: Bug
          area-path: 'MeijerTest'
          overwrite-area-path false: false
          iteration-path: 'MeijerTest'
          overwrite-iteration-path: false
          open-state: New
          close-state: Closed
          reopen-state: New
          veracode-api-id: ${{ secrets.VID }}
          veracode-api-key: ${{ secrets.VKEY }}
          veracode-app-profile: "test-action"
          scan-type: "Static Analysis and SCA"
          import-type: "All Unmitigated Flaws Violating Policy"
          custom-fields: "MyCustomField: Add a note here"
